FROM bitbucketpipelines/scala-sbt

RUN apt-get install -y unzip

COPY . /app

WORKDIR /app

RUN sbt dist

RUN unzip /app/target/universal/klassentrenner-1.0.zip 

ENTRYPOINT [ "bash", "klassentrenner-1.0/bin/klassentrenner", "-Dplay.http.secret.key='Vd=iSgvwzT=Q;<PKfEjx<4n:V:jQ0xo/6Z?`3ti<b_ZtuuJUbagfi>fPWAY68<`k'" ]